### ISSUE TITLE
Fail in requirements.txt

### ISSUE THREAD

**Issue by IDerr** [yongseokoh/nvme_exporter#1]
Hello, I have installed your exporter, it works great except for one small problem, 
the prometheus client referenced in your requirements.txt, is too old, and don't have the Info on the client

You just have to change the version to make it work !

root@owdavl:/home/owd/nvme_exporter# python3 nvme_exporter.py -p 9243 -u 10
Traceback (most recent call last):
  File "nvme_exporter.py", line 2, in <module>
    from prometheus_client import Info
ImportError: cannot import name 'Info' from 'prometheus_client' (/usr/local/lib/python3.7/dist-packages/prometheus_client/__init__.py)

Thanks a lot for your work !

**Comment by Carlotronics** [comment]
Hello,

I would add that it needs at least version `0.4.0`, which brings the "Info" module ([see changelog](https://github.com/prometheus/client_python/releases/tag/v0.4.0)).
